version: '3.9'
services:
  node:
    image: node:lts
    volumes:
      - .:/var/www/html:cached
      - ./db.json:/app/db.json:delegated
    working_dir: /var/www/html
    ports:
      - '8000:8000'
      - '3000:3000'
    command: bash -c "yarn json-server db.json --host 0.0.0.0--port 3000"
    tty: true

